[pytest]
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    smoke: smoke test
    regression: regression test
    system: system test
    ui: ui test
    api: api test
    negative: negative test
    positive: positive test
    authorization: authorization test
    registration: registration test
    courses: courses test
    users: users test
    dashboard: dashboard test
